-- Development profile seed data. Schema is generated by Hibernate
-- (spring.jpa.hibernate.ddl-auto=create-drop in application-dev.properties)
-- from the actual @Entity classes -- this file no longer hand-maintains
-- CREATE TABLE statements, which had drifted out of sync with several
-- entities across past features (missing tables, missing columns).

-- Insert a sample conference for UI/testing
INSERT INTO conferences (title, venue, start_date, end_date, is_active, blind_review, logo_url, contact_email, created_at, updated_at)
VALUES ('Research Conference 2025', 'Virtual / Example Venue', '2025-11-01', '2025-11-30', TRUE, FALSE, 'https://example.com/logo.png', 'info@example.org', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Password hashes generated with BCrypt (work factor ~10) for dev passwords
-- admin@example.com / admin
-- reviewer@example.com / reviewer
-- author@example.com / author
INSERT INTO users (email, password_hash, full_name, role, enabled, created_at, updated_at)
VALUES
('admin@example.com', '$2a$10$QxQmTnWb0k1uL3s4R6zQ5e8l7OqUu3R2m3tv5U6wOeJcT3r2A1y2K', 'Dev Admin', 'ADMIN', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('reviewer@example.com', '$2a$10$1PjvYwHkS8dV9bQe4r7uKuVfQeKX8f2rAqKQ7m1pWnYvT3b5Zc6rS', 'Dev Reviewer', 'REVIEWER', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('author@example.com', '$2a$10$wZxYvQpL9mBnC3dE7tFhYu6pQeR8tU1lM2nO5pQzR7sT8uV1wXyZa', 'Dev Author', 'AUTHOR', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Sub-themes for the sample conference
-- (steering_committee seed data removed: no @Entity maps this table anymore --
-- superseded by ConferenceCommitteeRole from the committee-roles feature)
INSERT INTO sub_themes (conference_id, name, description, created_at, updated_at)
VALUES (1, 'Machine Learning', 'Applications of ML in agriculture.', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Papers and related tables
INSERT INTO papers (conference_id, title, abstract_text, submitter_id, status, track, created_at, updated_at)
VALUES (1, 'Sample Paper on ML', 'This paper explores sample ML methods.', 3, 'ACCEPTED', 'Machine Learning', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO paper_versions (paper_id, version_number, file_path, original_filename, created_at, updated_at)
VALUES (1, 1, '/uploads/sample-paper.pdf', 'sample-paper.pdf', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO paper_authors (paper_id, full_name, email, affiliation, is_presenter, created_at, updated_at)
VALUES (1, 'Dev Author', 'author@example.com', 'Example University', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Review assignments and reviews
INSERT INTO review_assignments (paper_id, reviewer_id, assigned_at, due_date, status, created_at, updated_at)
VALUES (1, 2, CURRENT_TIMESTAMP(), NULL, 'PENDING', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO reviews (paper_id, reviewer_id, score, comments, confidential_comments, created_at, updated_at)
VALUES (1, 2, 4, 'Promising results in sample domain.', 'Confidential note.', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Registrations (kept minimal for dev)
INSERT INTO registrations (user_id, ticket_type, amount, payment_status, invoice_path, created_at, updated_at)
VALUES (3, 'Academic', 0.00, 'PAID', NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- ==============================
-- Additional demo data (history)
-- ==============================

-- More conferences (kept inactive for history)
INSERT INTO conferences (title, venue, start_date, end_date, is_active, blind_review, logo_url, contact_email, created_at, updated_at)
VALUES ('Research Conference 2026', 'Colombo, Sri Lanka', '2026-08-10', '2026-08-12', FALSE, FALSE, 'https://example.com/logo-2026.png', 'info2026@example.org', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO conferences (title, venue, start_date, end_date, is_active, blind_review, logo_url, contact_email, created_at, updated_at)
VALUES ('Research Conference 2024', 'Bangkok, Thailand', '2024-09-05', '2024-09-07', FALSE, FALSE, 'https://example.com/logo-2024.png', 'info2024@example.org', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Sub-themes for 2026 and 2024
INSERT INTO sub_themes (conference_id, name, description, created_at, updated_at)
SELECT c.id, 'Sustainability', 'Sustainable practices in agri-food systems.', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM conferences c WHERE c.title='Research Conference 2026';

INSERT INTO sub_themes (conference_id, name, description, created_at, updated_at)
SELECT c.id, 'Data Science', 'Data and analytics for agriculture.', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM conferences c WHERE c.title='Research Conference 2024';

-- More users (for assignments and richer demo)
INSERT INTO users (email, password_hash, full_name, role, enabled, created_at, updated_at)
VALUES
('chair@example.com', '', 'Track Chair', 'ADMIN', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('author2@example.com', '', 'Second Author', 'AUTHOR', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('reviewer2@example.com', '', 'Second Reviewer', 'REVIEWER', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Additional papers by authors
INSERT INTO papers (conference_id, title, abstract_text, submitter_id, status, track, created_at, updated_at)
SELECT 1, 'Precision Agriculture with Drones', 'Explores drone-based crop monitoring.', u.id, 'UNDER_REVIEW', 'Sustainability', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM users u WHERE u.email='author2@example.com';

INSERT INTO papers (conference_id, title, abstract_text, submitter_id, status, track, created_at, updated_at)
SELECT 1, 'AI for Crop Yield Prediction', 'Predictive models for yield.', u.id, 'SUBMITTED', 'Data Science', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM users u WHERE u.email='author@example.com';

-- Versions for the new papers
INSERT INTO paper_versions (paper_id, version_number, file_path, original_filename, created_at, updated_at)
SELECT p.id, 1, '/uploads/drones-v1.pdf', 'drones-v1.pdf', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p WHERE p.title='Precision Agriculture with Drones';

INSERT INTO paper_versions (paper_id, version_number, file_path, original_filename, created_at, updated_at)
SELECT p.id, 2, '/uploads/drones-v2.pdf', 'drones-v2.pdf', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p WHERE p.title='Precision Agriculture with Drones';

INSERT INTO paper_versions (paper_id, version_number, file_path, original_filename, created_at, updated_at)
SELECT p.id, 1, '/uploads/yield-v1.pdf', 'yield-v1.pdf', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p WHERE p.title='AI for Crop Yield Prediction';

-- Authors for the new papers
INSERT INTO paper_authors (paper_id, full_name, email, affiliation, is_presenter, created_at, updated_at)
SELECT p.id, 'Second Author', 'author2@example.com', 'AgriTech Labs', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p WHERE p.title='Precision Agriculture with Drones';

INSERT INTO paper_authors (paper_id, full_name, email, affiliation, is_presenter, created_at, updated_at)
SELECT p.id, 'Dev Author', 'author@example.com', 'Example University', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p WHERE p.title='AI for Crop Yield Prediction';

-- Assign reviewers and add reviews
INSERT INTO review_assignments (paper_id, reviewer_id, assigned_at, due_date, status, created_at, updated_at)
SELECT p.id, u.id, CURRENT_TIMESTAMP(), NULL, 'PENDING', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p JOIN users u ON u.email='reviewer2@example.com'
WHERE p.title='Precision Agriculture with Drones';

INSERT INTO reviews (paper_id, reviewer_id, score, comments, confidential_comments, created_at, updated_at)
SELECT p.id, u.id, 5, 'Excellent clarity and methodology.', 'Consider blind spots in data.', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p JOIN users u ON u.email='reviewer2@example.com'
WHERE p.title='Precision Agriculture with Drones';

INSERT INTO review_assignments (paper_id, reviewer_id, assigned_at, due_date, status, created_at, updated_at)
SELECT p.id, u.id, CURRENT_TIMESTAMP(), NULL, 'PENDING', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p JOIN users u ON u.email='reviewer@example.com'
WHERE p.title='AI for Crop Yield Prediction';

INSERT INTO reviews (paper_id, reviewer_id, score, comments, confidential_comments, created_at, updated_at)
SELECT p.id, u.id, 3, 'Good baseline; needs more experiments.', 'Check data leakage.', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM papers p JOIN users u ON u.email='reviewer@example.com'
WHERE p.title='AI for Crop Yield Prediction';

-- Registration for the additional user
INSERT INTO registrations (user_id, ticket_type, amount, payment_status, invoice_path, created_at, updated_at)
SELECT u.id, 'Academic', 0.00, 'PENDING', NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM users u WHERE u.email='author2@example.com';
